# Generated by Django 5.2.6 on 2026-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
