# Generated by Django 5.2.6 on 2026-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_otp_sent_at',
            new_name='last_2fa_otp_sent_at',
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_change_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_verification_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
